### ISSUE TITLE
Hardcoded tab size

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-lemminx#1]
https://github.com/sublimelsp/LSP-lemminx/blob/46a816320e09df1b91cd2186fbc31a513e9348ad/LSP-lemminx.sublime-settings#L58
We could dynamically update it like we do for LSP-vue:
https://github.com/sublimelsp/LSP-vue/blob/077e48b525dd8387a488a926d38ed03d8c5a4bf7/plugin.py#L59-L62

**Comment by deathaxe** [comment]
Good point. Basicallly the current settings are just a copy of the defaults provided by the language server to have some kind of reference.

The main issue with the current way of handling settings is just that updating settings via code would disable a user to setup custom values, if required.

The settings injected by all the LSP-xxxx plugins act as normal client settings already. This means a user must not add client settings to the global LSP.sublime-settings file as this would vanish the "defaults". Injecting values after loading them from LSP-xxxx.sublime-settings ovrerrides any user settings.

We may argue about whether a user ever wants to setup different values than those from Preferences or syntax speciffic settings, but it at least increases fragmentation of settings.

IMHO any LSP-xxx plugin should just add its values to LSP's `default_clients` key. This would enable the plugin to safely provide constant values or those dynamically derived from sublime settings. A user could still add specific client settings to LSP.sublime-settings then.

Alternatively or anyway we might need a better way to do a "deep update" of such nested settings objects. With a look at other editors the nested json objects should propably be replaced by something like `"xml.format.tabSize"` for instance and translated before sending to the server.

It would make updating/overriding settings much easier.

**Comment by rchl** [comment]
I'm up for using "dot notation" but with either solution it would be impossible to "remove" a setting completely (whether doing that would be needed or not is another matter. Probably it would work to just override it to null...).

**Comment by deathaxe** [comment]
I don't think removing settings by override is even needed. If it was defined in the defaults, it should keep. Otherwise the `null` override is a proper solution already used by sublime-theme and/or sublime-color-scheme.

**Comment by rchl** [comment]
I'm not sure I unederstand the part about `LSP-xxxx.sublime-settings` vs. `LSP.sublime-settings`.

They exist in different namespaces, I believe, so one doesn't affect the other. I mean, yes, LSP will merge client settings into the same object (I guess) but why would one want to define settings for the same client in both places?

Also, I prefer client-specific settings in separate files. Otherwise files get really big and it's more annoying IMO.

But yes, I don't fully get your point about mixing those settings.

**Comment by deathaxe** [comment]
> I believe, so one doesn't affect the other. 

Unfortunatelly they do. When I started to play with LSP-json my first impression was it to be a server-configuration-provider which just extends the lsp configuration. A helper which makes me not to need to add a new server configuration manually but by installing the extra package, with the nice give away to also automatically install all required resources.

So I expected customization to be done via LSP.sublime-settings' `"client"` key. Doing so resulted in all settings provided by the LSP-json plugin to be removed from LSP's config object.

> why would one want to define settings for the same client in both places?

Noone wants, but where is the correct place to do so? Today it is possible to edit settings for a server in two files LSP-xxxx.sublime-settings and LSP.sublime-settings. The latter one breaks the first one's defaults. The behavior is just weird. 

Furtermore to be honest: I don't like each plugin adding its own settings to main menu and command pallete nor do I like the spreading of settings.

When LSP started there was only one LSP.sublime-settings to configure all available language servers in. With upcomming LSP-extension-plugins those settings are more and more spread to many files, each of them having only few lines of code.

If this is the way to go it should at least be consequent. Means adding a `LSP-lemminx` key to LSP.sublime-settings' `client` key should not have any effect or even though an exception.

**Comment by rchl** [comment]
The setting is not hardcoded now, it's removed completely. Not sure what it means for the server but I guess this can be closed.
