### ISSUE TITLE
LemMinX exited with status code 3221226505

### ISSUE THREAD

**Issue by hevezolly** [sublimelsp/LSP-lemminx#14]
Hello!
I have a problem with LSP-LemMinX.
Basically, every time I'm oppening xml file in sublime text editor, LSP-lemminx writes me following:

![image](https://user-images.githubusercontent.com/28929816/164220725-475fc272-d3a8-4fb8-9a9a-c16a5e7dd616.png)

restarting plugin doesn't help, this window pops up again.
What does this error means? How to fix it?
I'd be grateful if someone help me

**Comment by rwols** [comment]
Do you have a Java runtime installed?

**Comment by hevezolly** [comment]
I see. I've accidently changed PATH, so path to java was incorrect. Now I fixed it and everything works. Thank you
